print("✨"*30)
print("🎉WELCOME TO YOUR PYTHON JOURNY!")
print("👑"*30)
print("today date: september 26,2025 ")
print("weeak: 1/48")
print("Journy started!🐍")
name = input("What's your name?")
print(f"Hello,{name}!Welcome to day 1 of your python adventure!")
goal = input("What do you want to achive With python?")
print(f"Amazing! you will achive '{goal}'in 48 Weeks!")
print("Let's start coding! 🚀🐍")