print("====Variable practice=====")
my_name =input("Enter your name:")
my_age =input("Enter your age:")
my_city =input("Enter your city:")
favorite_language =input("Enter your favorite programming language:")
print(f"my name is {my_name}")
print(f"I am {my_age} years old")
print(f"I live in {my_city}")
print(f"My favarite programing language is {favorite_language}")
birth_year = 2025-int(my_age)
print(f"I was born around {birth_year:}") 